#!c:\Users\Mudit\Documents\ASU\Classes\Fall 2024\EGR334\spleeter_env\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
